**LOAN PREDICTION....**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
loan_df = pd.read_csv('/content/train_u6lujuX_CVtuZ9i (1).csv');
#loan_df.head()
loan_df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [4]:
loan_df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
loan_df = loan_df.dropna()
loan_df.isnull().sum()
loan_df.shape
loan_df.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y

In [6]:
loan_df.groupby("Property_Area").describe()

              ApplicantIncome                                            \
                        count         mean          std     min     25%
Property_Area
Rural                   139.0  5764.697842  7326.415997   150.0  2967.5
Semiurban               191.0  5368.068063  5649.111499  1500.0  2840.5
Urban                   150.0  4988.246667  3547.964186  1000.0  2903.5

                                        CoapplicantIncome               ...  \
                  50%      75%      max             count         mean  ...
Property_Area                                                           ...
Rural          4106.0  6233.00  81000.0             139.0  1576.583597  ...
Semiurban      3859.0  5376.50  39999.0             191.0  1554.324607  ...
Urban          3505.0  5988.75  18333.0             150.0  1619.358667  ...

              Loan_Amount_Term        Credit_History                           \
                           75%    max          count      mean       std  min
Property_Area
Rural                    360.0  480.0          139.0  0.841727  0.366317  0.0
Semiurban                360.0  480.0          191.0  0.874346  0.332331  0.0
Urban                    360.0  480.0          150.0  0.840000  0.367834  0.0


               25%  50%  75%  max
Property_Area
Rural          1.0  1.0  1.0  1.0
Semiurban      1.0  1.0  1.0  1.0
Urban          1.0  1.0  1.0  1.0

[3 rows x 40 columns]

In [7]:
loan_df = loan_df.drop(['Loan_ID'],axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
loan_df['Gender'] = encoder.fit_transform(loan_df['Gender'])
loan_df['Married'] = encoder.fit_transform(loan_df['Married'])
loan_df['Education'] = encoder.fit_transform(loan_df['Education'])
loan_df['Self_Employed'] = encoder.fit_transform(loan_df['Self_Employed'])
loan_df['Property_Area'] = encoder.fit_transform(loan_df['Property_Area'])
loan_df['Loan_Status'] = encoder.fit_transform(loan_df['Loan_Status'])
loan_df = loan_df.replace(to_replace='3+', value=4)

In [9]:
loan_df.head(20)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1
5,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,2,1
6,1,1,0,1,0,2333,1516.0,95.0,360.0,1.0,2,1
7,1,1,4,0,0,3036,2504.0,158.0,360.0,0.0,1,0
8,1,1,2,0,0,4006,1526.0,168.0,360.0,1.0,2,1
9,1,1,1,0,0,12841,10968.0,349.0,360.0,1.0,1,0
10,1,1,2,0,0,3200,700.0,70.0,360.0,1.0,2,1
12,1,1,2,0,0,3073,8106.0,200.0,360.0,1.0,2,1
13,1,0,0,0,0,1853,2840.0,114.0,360.0,1.0,0,0
14,1,1,2,0,0,1299,1086.0,17.0,120.0,1.0,2,1
15,1,0,0,0,0,4950,0.0,125.0,360.0,1.0,2,1
17,0,0,0,0,0,3510,0.0,76.0,360.0,0.0,2,0
18,1,1,0,1,0,4887,0.0,133.0,360.0,1.0,0,0
20,1,1,0,1,0,7660,0.0,104.0,360.0,0.0,2,0
21,1,1,1,0,0,5955,5625.0,315.0,360.0,1.0,2,1
22,1,1,0,1,0,2600,1911.0,116.0,360.0,0.0,1,0
25,1,1,0,0,1,9560,0.0,191.0,360.0,1.0,1,1

In [10]:
loan_df['Dependents'] = loan_df['Dependents'].astype(int)

In [11]:
loan_df["Dependents"].describe()

count    480.000000
mean       0.862500
std        1.225107
min        0.000000
25%        0.000000
50%        0.000000
75%        2.000000
max        4.000000
Name: Dependents, dtype: float64

In [12]:
Y = loan_df['Loan_Status']
X = loan_df.drop(['Loan_Status'],axis=1)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [14]:
from sklearn import svm
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [15]:
from sklearn.metrics import accuracy_score
# accuracy score on test data
X_test_prediction = classifier.predict(x_test)
test_data_accuray = accuracy_score(X_test_prediction,y_test)
print('Accuracy on testing data : ', test_data_accuray)

Accuracy on testing data :  0.8020833333333334

In [16]:
import pickle
pickle.dump(classifier, open('loanPrediction.pkl','wb'))

In [ ]:
y_test

In [19]:
classifier.predict(x_test)

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1])